loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  
  ingester:
    chunk_encoding: snappy
  querier:
    max_concurrent: 4
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 24h # 10 days retention

  storage:
    type: s3
    bucketNames:
        chunks: nb-mio-loki-01-chunks
        ruler: nb-mio-loki-01-ruler
        admin: nb-mio-loki-01-admin
    s3:
      endpoint: minio.minio.svc.cluster.local:9000
      secretAccessKey: <access-key>
      accessKeyId: <access-key-id>
      s3ForcePathStyle: true
      insecure: true

deploymentMode: Distributed

ingester:
  replicas: 3
  zoneAwareReplication:
     enabled: false
querier:
  replicas: 3
  maxUnavailable: 2
queryFrontend:
  replicas: 2
  maxUnavailable: 1
queryScheduler:
  replicas: 2
distributor:
  replicas: 3 
  maxUnavailable: 2
compactor:
  replicas: 1
indexGateway:
  replicas: 2
  maxUnavailable: 1

bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0

backend:
   replicas: 0
read:
   replicas: 0
write:
   replicas: 0

singleBinary:
   replicas: 0

gateway:
   service:
     type: LoadBalancer

minio:
  enabled: false
