# Custom values for the Vault Helm chart

global:
  namespace: vault
  tlsDisable: false

server:
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-tls/vault.ca
    VAULT_TLSCERT: /vault/userconfig/vault-tls/vault.crt
    VAULT_TLSKEY: /vault/userconfig/vault-tls/vault.key
  volumes:
    - name: userconfig-vault-tls
      secret:
        defaultMode: 420
        secretName: vault-tls
  volumeMounts:
    - mountPath: /vault/userconfig/vault-tls
      name: userconfig-vault-tls
      readOnly: true

  standalone:
    enabled: true
    config: |-
      ui = true
      listener "tcp" {
        tls_disable = 0
        address = "[::]:8200"
        cluster_address = "[::]:8201"

        tls_cert_file = "/vault/userconfig/vault-tls/vault.crt"
        tls_key_file  = "/vault/userconfig/vault-tls/vault.key"
        tls_client_ca_file = "/vault/userconfig/vault-tls/vault.ca"

        x_forwarded_for_authorized_addrs = ["0.0.0.0/0", "::/0"]
        x_forwarded_for_authorized_ports = "8200"
        x_forwarded_proto_authorized = true

        telemetry {
          unauthenticated_metrics_access = true
        }
      }

      storage "file" {
        path = "/vault/data"
      }

      telemetry {
        disable_hostname = true
        prometheus_retention_time = "24h"
      }

      api_addr = "https://vault.nibir.xyz"
      cluster_addr = "https://vault.nibir.xyz"

  dataStorage:
    enabled: true
    size: 4Gi
    storageClass: longhorn
    accessMode: ReadWriteOnce
    mountPath: /vault/data

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: vault.nibir.xyz
        paths:
          - /
        backend:
          service:
            name: vault
            port:
              number: 8200
    tls:
      - secretName: vault-tls-ingress
        hosts:
          - vault.nibir.xyz

ui:
  enabled: true
  serviceType: LoadBalancer
  publishNotReadyAddresses: true

serverTelemetry:
  serviceMonitor:
    enabled: true
    selectors:
      release: prometheus

injector:
  enabled: false

csi:
  enabled: false
